package com.illusion.app.data.backup

import kotlinx.serialization.Serializable

/**
 * What gets backed up: SMB sources (never the password - re-entered on import), favorites, and
 * watch history. The scanned library itself is deliberately excluded - it's derived data, cheaply
 * regenerated by a rescan, and would bloat the file for no benefit.
 */
@Serializable
data class BackupPayload(
    val version: Int = 1,
    val sources: List<BackupSource>,
    val favorites: List<BackupFavorite>,
    val watchProgress: List<BackupWatchProgress>
)

@Serializable
data class BackupSource(
    val displayName: String,
    val host: String,
    val share: String,
    val rootPath: String,
    val domain: String,
    val username: String
)

@Serializable
data class BackupFavorite(val stableId: String, val addedAt: Long, val media: BackupMediaRef? = null)

@Serializable
data class BackupMediaRef(val source: BackupSource, val filePath: String, val sizeBytes: Long)

@Serializable
data class BackupWatchProgress(
    val stableId: String,
    val positionMs: Long,
    val durationMs: Long,
    val watched: Boolean,
    val updatedAt: Long,
    val media: BackupMediaRef? = null
)
